// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYTQt77OQfGIUpKWxQcOIqe0IYJq4GY5Q',
    appId: '1:824832350131:web:b6aa7c9e353b9904d5ddc6',
    messagingSenderId: '824832350131',
    projectId: 'cmsc23-todo-app-sclee4',
    authDomain: 'cmsc23-todo-app-sclee4.firebaseapp.com',
    storageBucket: 'cmsc23-todo-app-sclee4.appspot.com',
    measurementId: 'G-4J2RP6E2HS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgjuNuaaH6JBfu48Vp7gJ_YYHRy88Noqs',
    appId: '1:824832350131:android:7d5235fa9ebe6117d5ddc6',
    messagingSenderId: '824832350131',
    projectId: 'cmsc23-todo-app-sclee4',
    storageBucket: 'cmsc23-todo-app-sclee4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWpevxNFL97iTOHtHiaFsqA8GBReAoSuI',
    appId: '1:824832350131:ios:0e220ca3d2570027d5ddc6',
    messagingSenderId: '824832350131',
    projectId: 'cmsc23-todo-app-sclee4',
    storageBucket: 'cmsc23-todo-app-sclee4.appspot.com',
    iosClientId: '824832350131-usoa5l7qucce09ijbbrnr3hbavfv4852.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWpevxNFL97iTOHtHiaFsqA8GBReAoSuI',
    appId: '1:824832350131:ios:0e220ca3d2570027d5ddc6',
    messagingSenderId: '824832350131',
    projectId: 'cmsc23-todo-app-sclee4',
    storageBucket: 'cmsc23-todo-app-sclee4.appspot.com',
    iosClientId: '824832350131-usoa5l7qucce09ijbbrnr3hbavfv4852.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}
